name: 'Edit PDF by ReportLab'
description: 'Edit PDF by ReportLab'
author: 'sksat <sksat@sksat.net>'

inputs:
  script:
    description: your script
    required: true
  output:
    description: output PDF
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/sksat/reportlab-action:v0.1.1'
  args:
    - ${{ inputs.script }}
    - ${{ inputs.output }}
